import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {

    'en_US':{
      "Book Chapter": "Book Chapter",
      "Author" : "Author",
      "SIGN UP": "SIGN UP",
      "Sign up/Login": "Sign up/Login",
      "ISBN": "ISBN",
      "Booking Detail": "Booking Detail",
      "Chapter": "Chapter",
      "Exercise": "Exercise",
      "step by step solution": "step by step solution",
      "Question": "Question",
      "Sorry Solution not found": "Sorry Solution not found",
      "Book Exercise": "Book Exercise",
      "No Data": "No Data",
      "Book Marked Items": "Book Marked Items",
      "Chap": "Chap",
      "Category Id Home": "Category Id Home",
      "Login First": "Login First",
      "Search for book by title,Author name or ISBN": "Search for book by title,Author name or ISBN",
      "Scan your textbook": "Scan your textbook",
      "Subscribed": "Subscribed",
      "Subscribe": "Subscribe",
      "My Books": "My Books",
      "All Subscribe Books": "All Subscribe Books",
      "Remove": "Remove",
      "Access now All Books Solution": "Access now All Books Solution",
      "Exit App?": "Exit App?",
      "Do you want to exit this App": "Do you want to exit this App",
      "No": "No",
      "Yes": "Yes",
      "Home": "Home",
      "Search using book title or ISBN": "Search using book title or ISBN",
      "Scan your Textbook": "Scan your Textbook",
      "Select Subject from below": "Select Subject from below",
      "Reset Password": "Reset Password",
      "Please enter and conform your": "Please enter and conform your",
      "new password": "new password",
      "Old Password": "Old Password",
      "Conform New Password": "Conform New Password",
      "Please Enter old password": "Please Enter old password",
      "Please Enter new password": "Please Enter new password",
      "RESET": "RESET",
      "Password Updated": "Password Updated",
      "Some error occur": "Some error occur",
      "Chapter Exercise": "Chapter Exercise",
      "Step": "Step",
      "Comments": "Comments",
      "Data Not Loaded": "Data Not Loaded",
      "Write a Comment": "Write a Comment",
      "Tittle": "Tittle",
      "Please subscribe to your": "Please subscribe to your",
      "favorable package for": "favorable package for",
      "complete solution": "complete solution",
      "SUBSCRIBE NOW": "SUBSCRIBE NOW",
      "Was this Solution Helpful?": "Was this Solution Helpful?",
      "Chapter Info": "Chapter Info",
      "Q1": "Q1",
      "Q2.2nd Question of Ex 1": "Q2.2nd Question of Ex 1",
      "Choose Subscription": "Choose Subscription",
      "AED": "AED",
      "My Profile": "My Profile",
      "Add Photo!": "Add Photo!",
      "Take Photo": "Take Photo",
      "Chose from Library": "Chose from Library",
      "Select Picture": "Select Picture",
      "Albums": "Albums",
      "Photos": "Photos",
      "Cancel": "Cancel",
      "Edit Profile": "Edit Profile",
      "Email": "Email",
      "Contact Number": "Contact Number",
      "Please Enter email": "Please Enter email",
      "Please Enter phone number": "Please Enter phone number",
      "Save": "Save",
      "Data Saved": "Data Saved",
      "Forgot your Password": "Forgot your Password",
      "please enter your email address": "please enter your email address",
      "to get a link or enter phone": "to get a link or enter phone",
      "Number to get a verification code": "Number to get a verification code",
      "SEND": "SEND",
      "Login": "Login",
      "Email/Phone Number": "Email/Phone Number",
      "Password": "Password",
      "Forgot Password?": "Forgot Password?",
      "Please Enter password": "Please Enter password",
      "Some error occour": "Some error occour",
      "or Sign in using": "or Sign in using",
      "Do not have an account?": "Do not have an account?",
      "Sign Up": "Sign Up",
      "Terms and Conditions": "Terms and Conditions",
      "Sing up/Login": "Sing up/Login",
      "LOGIN": "LOGIN",
      "SIGN UP": "SIGN UP",
      "OR": "OR",
      "SKIP": "SKIP",
      "My Subscriptions": "My Subscriptions",
      "Ilam Study Package": "Ilam Study Package",
      "Auto Renew": "Auto Renew",
      "Expire": "Expire",
      "Price": "Price",
      "ACCESS NOW ALL BOOK": "ACCESS NOW ALL BOOK",
      "SOLUTIONS": "SOLUTIONS",
      "No Data Found": "No Data Found",
      "Verify Code": "Verify Code",
      "Please check your messages & enter the verification code we just sent to you": "Please check your messages & enter the verification code we just sent to you",
      "RESEND": "RESEND",
      "Advance Search": "Advance Search",
      "Please Enter Detail": "Please Enter Detail",
      "Book Title": "Book Title",
      "Search by Book Title": "Search by Book Title",
      "Author Name": "Author Name",
      "Search by Author Name": "Search by Author Name",
      "Search by ISBN": "Search by ISBN",
      "SEARCH": "SEARCH",
      "Please Enter Book Name": "Please Enter Book Name",
      "Please Enter Book Author Name": "Please Enter Book Author Name",
      "Please Enter Isbn": "Please Enter Isbn",
      "Selected Text": "Selected Text",
      "First Name": "First Name",
      "Last Name": "Last Name",
      "Phone Number (Optional)": "Phone Number (Optional)",
      "Please Enter first name": "Please Enter first name",
      "Please Enter last name": "Please Enter last name",
      "Account created successfully": "Account created successfully",
      "Already have an account": "Already have an account",
      "Subscription Method": "Subscription Method",
      "Card Holder Name": "Card Holder Name",
      "Card Number": "Card Number",
      "VALID THRU": "VALID THRU",
      "PAY NOW": "PAY NOW",
      "Pay": "Pay",
      "We ACCEPT": "We ACCEPT",
      "Flutter Demo": "Flutter Demo",
      "YY": "YY",
      "MM": "MM",
      "CVV": "CVV",
      "ARE YOU SURE TO EXIT FROM APP?": "ARE YOU SURE TO EXIT FROM APP?",
      "Theme Change": "Theme Change",
      "Dark Theme": "Dark Theme",
      'Author:':"Author:",
      "ISBN:":"ISBN:",
      "Scan your Textbook":"Scan your Textbook",
      "Forgot your Password ?":"Forgot your Password ?"
    },

    'ar_IQ':{
      "Forgot your Password ?":"نسيت رقمك السري ؟",
      "Book Chapter": "فصل الكتاب",
      "Author" : "مؤلف",
      "ISBN": "رقم ISBN",
      "SIGN UP": "اشتراك",
      "Sign up/Login": "اشترك تسجيل الدخول",
      "Booking Detail": "تفاصيل الحجز",
      "Chapter": "الفصل",
      "Exercise": "يمارس",
      "step by step solution": "حل خطوة بخطوة",
      "Question": "سؤال",
      "Sorry Solution not found": "عذرا الحل غير موجود",
      "Book Exercise": "تمرين الكتاب",
      "No Data": "لايوجد بيانات",
      "Book Marked Items": "كتاب العناصر المميزة",
      "Chap": "الفصل",
      "Category Id Home": "معرف الفئة الصفحة الرئيسية",
      "Login First": "سجل الدخول أولا",
      "Search for book by title,Author name or ISBN": "ابحث عن الكتاب حسب العنوان أو اسم المؤلف أو رقم ISBN",
      "Scan your textbook": "قم بمسح كتابك الدراسي",
      "Subscribed": "مشترك",
      "Subscribe": "الإشتراك",
      "My Books": "كتبي",
      "All Subscribe Books": "جميع الكتب الاشتراك",
      "Remove": "يزيل",
      "Access now All Books Solution": "الوصول الآن كل حل الكتب",
      "Exit App?": "هل تريد الخروج من التطبيق؟",
      "Do you want to exit this App": "هل تريد الخروج من هذا التطبيق",
      "No": "رقم",
      "Yes": "نعم",
      "Home": "مسكن",
      "Search using book title or ISBN": "ابحث باستخدام عنوان الكتاب أو رقم ISBN",
      "Select Subject from below": "حدد الموضوع من الاسفل",
      "Reset Password": "إعادة تعيين كلمة المرور",
      "Please enter and conform your": "الرجاء إدخال وتطابق الخاص بك",
      "new password": "كلمة سر جديدة",
      "Old Password": "كلمة المرور القديمة",
      "Conform New Password": "تطابق كلمة المرور الجديدة",
      "Please Enter old password": "الرجاء إدخال كلمة المرور القديمة",
      "Please Enter new password": "الرجاء إدخال كلمة مرور جديدة",
      "RESET": "إعادة تعيين",
      "Password Updated": "تم تحديث كلمة السر",
      "Some error occur": "يحدث خطأ ما",
      "Chapter Exercise": "تمرين الفصل",
      "Step": "خطوة",
      "Comments": "تعليقات",
      "Data Not Loaded": "البيانات غير محملة",
      "Write a Comment": "أكتب تعليقا",
      "Tittle": "تيتل",
      "Please subscribe to your": "يرجى الاشتراك في",
      "favorable package for": "حزمة مواتية ل",
      "complete solution": "الحل الكامل",
      "SUBSCRIBE NOW": "إشترك الآن",
      "Was this Solution Helpful?": "هل كان هذا الحل مفيدًا؟",
      "Chapter Info": "معلومات الفصل",
      "Q1": "س 1",
      "Q2.2nd Question of Ex 1": "س 2. السؤال الثاني في المثال 1",
      "Choose Subscription": "اختر الاشتراك",
      "AED": "درهم إماراتي",
      "My Profile": "ملفي",
      "Add Photo!": "إضافة صورة!",
      "Take Photo": "تصوير",
      "Chose from Library": "اختار من المكتبة",
      "Select Picture": "حدد صورة",
      "Albums": "ألبومات",
      "Photos": "الصور",
      "Cancel": "يلغي",
      "Edit Profile": "تعديل الملف الشخصي",
      "Email": "بريد إلكتروني",
      "Contact Number": "رقم الاتصال",
      "Please Enter email": "الرجاء إدخال البريد الإلكتروني",
      "Please Enter phone number": "الرجاء إدخال رقم الهاتف",
      "Save": "يحفظ",
      "Data Saved": "البيانات المحفوظة",
      "Forgot your Password": "نسيت كلمة السر",
      "please enter your email address": "الرجاء إدخال عنوان البريد الإلكتروني الخاص بك",
      "to get a link or enter phone": "للحصول على ارتباط أو إدخال الهاتف",
      "Number to get a verification code": "الرقم للحصول على رمز التحقق",
      "SEND": "إرسال",
      "Login": "تسجيل الدخول",
      "Email/Phone Number": "البريد الإلكتروني / رقم الهاتف",
      "Password": "كلمة المرور",
      "Forgot Password?": "هل نسيت كلمة السر؟",
      "Please Enter password": "الرجاء إدخال كلمة المرور",
      "Some error occour": "حدث خطأ ما",
      "or Sign in using": "أو تسجيل الدخول باستخدام",
      "Do not have an account?": "لا تملك حساب؟",
      "Sign Up": "اشتراك",
      "Terms and Conditions": "الأحكام والشروط",
      "OR": "أو",
      "SKIP": "تخطى",
      "My Subscriptions": "اشتراكاتي",
      "Ilam Study Package": "حزمة دراسة إيلام",
      "Auto Renew": "يجدد ذاتيا",
      "Expire": "تنقضي",
      "Price": "السعر",
      "ACCESS NOW ALL BOOK": "الوصول الآن إلى كل الكتاب",
      "SOLUTIONS": "حلول",
      "No Data Found": "لاتوجد بيانات",
      "Verify Code": "التحقق من كود",
      "Please check your messages & enter the verification code we just sent to you": "يرجى التحقق من رسائلك وإدخال رمز التحقق الذي أرسلناه لك للتو",
      "RESEND": "إعادة إرسال",
      "Advance Search": "البحث المتقدم",
      "Please Enter Detail": "الرجاء إدخال التفاصيل",
      "Book Title": "عنوان كتاب",
      "Search by Book Title": "البحث عن طريق عنوان الكتاب",
      "Author Name": "اسم المؤلف",
      "Search by Author Name": "البحث عن طريق اسم المؤلف",
      "Search by ISBN": "البحث عن طريق رقم ISBN",
      "SEARCH": "بحث",
      "Please Enter Book Name": "الرجاء إدخال اسم الكتاب",
      "Please Enter Book Author Name": "الرجاء إدخال اسم مؤلف الكتاب",
      "Please Enter Isbn": "الرجاء إدخال Isbn",
      "Selected Text": "نص محدد",
      "First Name": "الاسم الاول",
      "Last Name": "الكنية",
      "Phone Number (Optional)": "رقم الهاتف (اختيارى)",
      "Please Enter first name": "الرجاء إدخال الاسم الأول",
      "Please Enter last name": "الرجاء إدخال الاسم الأخير",
      "Account created successfully": "تم إنشاء الحساب بنجاح",
      "Already have an account?": "هل لديك حساب؟",
      "Subscription Method": "طريقة الاشتراك",
      "Card Holder Name": "إسم صاحب البطاقة",
      "Card Number": "رقم البطاقة",
      "VALID THRU": "صالح من خلال",
      "PAY NOW": "ادفع الآن",
      "Pay": "دفع",
      "We ACCEPT": "نحن نقبل",
      "Flutter Demo": "عرض Flutter",
      "YY": "YY",
      "MM": "MM",
      "CVV": "CVV",
      "ARE YOU SURE TO EXIT FROM APP?": "هل أنت متأكد من الخروج من التطبيق؟",
      "Theme Change": "تغيير الموضوع",
      "Dark Theme": "مظهر داكن",
      "Author:":"مؤلف:",
      "ISBN:" : "رقم ال ISBN:",
      "Scan your Textbook":"مسح الكتاب الدراسي الخاص بك"
    }

  };
}